poly_in_str = ["x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT FOUR} + x\N{SUPERSCRIPT THREE} + x + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT FOUR} + x\N{SUPERSCRIPT THREE} + x\N{SUPERSCRIPT TWO} + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT FIVE} + x\N{SUPERSCRIPT THREE} + x + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT FIVE} + x\N{SUPERSCRIPT THREE} + x\N{SUPERSCRIPT TWO} + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT FIVE} + x\N{SUPERSCRIPT FOUR} + x\N{SUPERSCRIPT THREE} + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT FIVE} + x\N{SUPERSCRIPT FOUR} + x\N{SUPERSCRIPT THREE} + x\N{SUPERSCRIPT TWO} + x + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT SIX} + x\N{SUPERSCRIPT THREE} + x\N{SUPERSCRIPT TWO} + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT SIX} + x\N{SUPERSCRIPT FOUR} + x\N{SUPERSCRIPT THREE} + x\N{SUPERSCRIPT TWO} + x + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT SIX} + x\N{SUPERSCRIPT FIVE} + x + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT SIX} + x\N{SUPERSCRIPT FIVE} + x\N{SUPERSCRIPT TWO} + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT SIX} + x\N{SUPERSCRIPT FIVE} + x\N{SUPERSCRIPT THREE} + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT SIX} + x\N{SUPERSCRIPT FIVE} + x\N{SUPERSCRIPT FOUR} + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT SIX} + x\N{SUPERSCRIPT FIVE} + x\N{SUPERSCRIPT FOUR} + x\N{SUPERSCRIPT TWO} + x + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT SIX} + x\N{SUPERSCRIPT FIVE} + x\N{SUPERSCRIPT FOUR} + x\N{SUPERSCRIPT THREE} + x + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT SEVEN} + x\N{SUPERSCRIPT TWO} + x + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT SEVEN} + x\N{SUPERSCRIPT THREE} + x + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT SEVEN} + x\N{SUPERSCRIPT THREE} + x\N{SUPERSCRIPT TWO} + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT SEVEN} + x\N{SUPERSCRIPT FOUR} + x\N{SUPERSCRIPT THREE} + x\N{SUPERSCRIPT TWO} + x + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT SEVEN} + x\N{SUPERSCRIPT FIVE} + x\N{SUPERSCRIPT FOUR} + x\N{SUPERSCRIPT THREE} + x\N{SUPERSCRIPT TWO} + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT SEVEN} + x\N{SUPERSCRIPT SIX} + x + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT SEVEN} + x\N{SUPERSCRIPT SIX} + x\N{SUPERSCRIPT THREE} + x\N{SUPERSCRIPT TWO} + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT SEVEN} + x\N{SUPERSCRIPT SIX} + x\N{SUPERSCRIPT FOUR} + x\N{SUPERSCRIPT TWO} + x + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT SEVEN} + x\N{SUPERSCRIPT SIX} + x\N{SUPERSCRIPT FOUR} + x\N{SUPERSCRIPT THREE} + x\N{SUPERSCRIPT TWO} + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT SEVEN} + x\N{SUPERSCRIPT SIX} + x\N{SUPERSCRIPT FIVE} + x\N{SUPERSCRIPT TWO} + x + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT SEVEN} + x\N{SUPERSCRIPT SIX} + x\N{SUPERSCRIPT FIVE} + x\N{SUPERSCRIPT FOUR} + x + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT SEVEN} + x\N{SUPERSCRIPT SIX} + x\N{SUPERSCRIPT FIVE} + x\N{SUPERSCRIPT FOUR} + x\N{SUPERSCRIPT TWO} + 1",
               "x\N{SUPERSCRIPT EIGHT} + x\N{SUPERSCRIPT SEVEN} + x\N{SUPERSCRIPT SIX} + x\N{SUPERSCRIPT FIVE} + x\N{SUPERSCRIPT FOUR} + x\N{SUPERSCRIPT THREE} + 1"]


poly = [0x11B, 0x11D, 0x12B, 0x12D, 0x139, 0x13F,
        0x14D, 0x15F, 0x163, 0x165, 0x169, 0x171,
        0x177, 0x17B, 0x187, 0x18B, 0x18D, 0x19F,
        0x1BD, 0x1C3, 0x1CD, 0x1D7, 0x1DD, 0x1E7,
        0x1F3, 0x1F5, 0x1F9]


for i in range(len(poly)):
    print(i)
    print(poly[i])
    print("/--/--/--/--/")